[build]
  command = "npm run build"
  functions = "functions-build"
  publish = "public"

[[redirects]]
  from = "/2015/05/01/react-in-your-react-native-webview-so-you-can-react-while-you-react.html"
  to = "/react-in-your-react-native-webview-so-you-can-react-while-you-react/"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "*"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"
    Access-Control-Allow-Credentials = "true"

[[headers]]
  for = "/.well-known/webfinger"
  [headers.values]
    Content-Type = "application/json"

[[headers]]
  for = "/actor"
  [headers.values]
    Content-Type = "application/activity+json"
